name: movie_time
description: "A movie recommendation app"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  shared_preferences: ^2.3.4
  http: ^1.2.2
  shimmer: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/profile.jpg

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit.ttf

flutter_native_splash:
  background_image: "assets/images/gradient_background.png"
  image: assets/images/logo.png
